services:
  spoolman: # Spoolman-Anwendung
    image: ghcr.io/donothingloop/spoolman:latest
    container_name: spoolman
    ports:
      - "8000:8000" # Spoolman erreichbar über Port 8000 deines Hosts
    volumes:
      - spoolman_data:/app/data # **Speichert Konfiguration persistent**
    environment:
      # **Wichtig: Datenbankverbindung zu PostgreSQL herstellen**
      # Ersetze 'your_secure_password' mit einem SICHEREN Passwort!
      - DATABASE_URL=postgresql://spoolman_user:your_secure_password@db:5432/spoolman_db
    depends_on:
      - db # Stellt sicher, dass die Datenbank vor Spoolman startet
    restart: unless-stopped

  db: # PostgreSQL-Datenbank
    image: postgres:13-alpine
    container_name: spoolman_db
    environment:
      # **Wichtig: PostgreSQL-Zugangsdaten festlegen**
      # Ersetze 'your_secure_password' mit einem SICHEREN Passwort!
      - POSTGRES_DB=spoolman_db
      - POSTGRES_USER=spoolman_user
      - POSTGRES_PASSWORD=your_secure_password
    volumes:
      - db_data:/var/lib/postgresql/data # **Speichert Datenbankdaten persistent**
    restart: unless-stopped

volumes:
  spoolman_data:
  db_data: