services:
  dockge: # Definition des Dockge-Services
    image: louislam/dockge:1 # Das zu verwendende Docker-Image
    restart: unless-stopped # Neustart-Richtlinie: Container wird automatisch neu gestartet, außer wenn er manuell gestoppt wurde
    ports: # Port-Mapping zwischen Host und Container
      - 5001:5001 # Port 5001 auf dem Host wird auf Port 5001 im Container gemappt
    volumes: # Volume-Mappings zwischen Host und Container
      - /var/run/docker.sock:/var/run/docker.sock # Bindet den Docker-Socket für die Docker-Verwaltung innerhalb von Dockge
      - ./data:/app/data # Bindet das lokale Verzeichnis './data' an das Datenverzeichnis
      # - /root/.docker/:/root/.docker # Optionale Bindung des Docker-Authentifizierungsverzeichnisses für private Registries
      - /opt/stacks:/opt/stacks # Bindet das Verzeichnis '/opt/stacks' auf dem Host an das Stacks-Verzeichnis von Dockge (ACHTUNG: Pfade müssen übereinstimmen!)
    environment: # Umgebungsvariablen für den Container
      - DOCKGE_STACKS_DIR=/opt/stacks # Gibt das Stacks-Verzeichnis an, das von Dockge verwendet wird

# Keine benannten Volumes definiert, da alle Volumes als Bind-Mounts verwendet werden.