# Definition der benannten Volumes
volumes:
  work: # Volume für die Arbeitsdaten von AdGuard Home
  conf: # Volume für die Konfigurationsdaten von AdGuard Home

services:
  adguardhome: # Definition des AdGuard Home Service
    image: adguard/adguardhome # Das zu verwendende Docker-Image
    container_name: adguardhome # Der Name des Containers
    ports: # Port-Mappings zwischen Host und Container
      - 53:53/tcp  # DNS (TCP)
      - 53:53/udp  # DNS (UDP)
      - 67:67/udp  # DHCP (UDP)
      - 68:68/tcp  # DHCP Client (TCP)
      - 68:68/udp  # DHCP Client (UDP)
      - 853:853/tcp # DNS over TLS (DoT)
      - 5443:5443/tcp # DNS over HTTPS (DoH) (TCP)
      - 5443:5443/udp # DNS over HTTPS (DoH) (UDP)
      - 784:784/udp # DNS over QUIC (DoQ)
      - 8853:8853/udp # DNS over QUIC (DoQ)
      - 80:80/tcp   # Web-Interface (TCP), geändert von 80:80, falls Port 80 bereits belegt ist
      - 3000:3000/tcp # Web-Interface (TCP) (alternative Port)
    volumes: # Volume-Mappings zwischen Host und Container
      - work:adguardhome/work   # Bindet das 'work' Volume an das Arbeitsverzeichnis des Containers
      - conf:adguardhome/conf   # Bindet das 'conf' Volume an das Konfigurationsverzeichnis des Containers
    restart: unless-stopped # Neustart-Richtlinie: Container wird automatisch neu gestartet, außer wenn er manuell gestoppt wurde
